create database Retail_Sales;
use Retail_sales;

create table Retail_sales_table
	(
	transactions_id int primary key,
	sale_date date,
	sale_time time,
	customer_id	int,
    gender Varchar(256),	
    age int,
	category	Varchar(256),
    quantiy int,
	price_per_unit float,
    cogs float,
	total_sale float
    );

select * from Retail_sales_table;

select count(*) from Retail_sales_table;

select * from  Retail_sales_table
limit 20;


-- Data cleaning

select count(customer_id) from Retail_sales_table;

select * from Retail_sales_table
where transactions_id is null
or sale_date  is null
or sale_time is null
or customer_id	is null 
or gender is null
or age is null
or category is null
or quantiy is null
or price_per_unit is null
or  cogs is null
or total_sale is null;

-- Data Exploration 

-- How many sales we have?
SELECT  COUNT(*) As Total_sale FROM Retail_sales_table;

-- How many uniuque customers we have ?
SELECT COUNT(DISTINCT customer_id) FROM Retail_sales_table;

SELECT COUNT(DISTINCT gender) FROM Retail_sales_table;

SELECT DISTINCT category FROM Retail_sales_table;

-- Data Analysis & Business Key Problems & Answers

-- My Analysis & Findings
-- Q.1 Write a SQL query to retrieve all columns for sales made on '2022-11-05
-- Q.2 Write a SQL query to retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 10 in the month of Nov-2022
-- Q.3 Write a SQL query to calculate the total sales (total_sale) for each category.
-- Q.4 Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.
-- Q.5 Write a SQL query to find all transactions where the total_sale is greater than 1000.
-- Q.6 Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.
-- Q.7 Write a SQL query to calculate the average sale for each month. Find out best selling month in each year
-- Q.8 Write a SQL query to find the top 5 customers based on the highest total sales 
-- Q.9 Write a SQL query to find the number of unique customers who purchased items from each category.
-- Q.10 Write a SQL query to calculate the total revenue (total_sale) generated by male vs. female customers;

-- Q.1 Write a SQL query to retrieve all columns for sales made on '2022-11-05
SELECT * FROM Retail_sales_table
	WHERE sale_date = '2022-11-05';

-- Q.2 Write a SQL query to retrieve all transactions where the category is 'Clothing' 
-- and the quantity sold is more than 10 in the month of Nov-2022
SELECT * FROM  Retail_sales_table
	WHERE category = 'clothing' 
	AND quantiy > 10 
	AND sale_date >= '2022-11-01' 
	AND sale_date <= '2022-11-30';

-- Q.3 Write a SQL query to calculate the total sales (total_sale) for each category.
SELECT  SUM(total_sale) ,category, COUNT(*) As Total_orders 
	FROM Retail_sales_table
       	GROUP BY 2;

-- Q.4 Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.
SELECT ROUND(AVG(age),2) As Average_Age , category 
	FROM Retail_sales_table
   	 WHERE category = 'Beauty'; 

-- Q.5 Write a SQL query to find all transactions where the total_sale is greater than 1000.
SELECT * FROM Retail_sales_table
	WHERE total_sale > 1000;

-- Q.6 Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.
SELECT COUNT(transactions_id) , gender, category FROM Retail_sales_table
	GROUP BY gender, category
   	 ORDER BY category;

-- Q.7 Write a SQL query to calculate the average sale for each month. Find out best selling month in each year;
SELECT YEAR  (sale_date) As Year , Month (sale_date) As Month,Round(Avg (Total_sale),2) As Avg_sale 
		FROM Retail_sales_table
        GROUP BY YEAR (sale_date) , MONTH (sale_date)
        ORDER BY YEAR , MONTH;
    
-- Q.8 Write a SQL query to find the top 5 customers based on the highest total sales;
SELECT  customer_id, sum(Total_sale) As Total_sale FROM Retail_sales_table
	GROUP BY customer_id
	ORDER BY total_sale 
	DESC LIMIT  5;

-- Q.9 Write a SQL query to find the number of unique customers who purchased items from each category.
SELECT category, COUNT(DISTINCT customer_id) AS unique_customers
	FROM retail_sales_table
	GROUP BY category
   	 ORDER BY unique_customers DESC;

-- Q.10 Write a SQL query to calculate the total revenue (total_sale) generated by male vs. female customers;
SELECT gender,SUM(total_sale) AS total_revenue
FROM retail_sales_table
GROUP BY gender
ORDER BY total_revenue DESC;









